---
title: Developmental changes in the speed of social attention in early word 
  learning -- Experiment 3
author: Daniel Yurovsky, Anna Wade, Allison M Krauss, Grace W. Gengoux, 
  Antonio Hardan, & Michael C Frank
date: "`r Sys.Date()`"
output:
  html_document:
    highlight: tango
    theme: spacelab
---

<style type="text/css">
.table {

    width: 40%;
}
</style>

```{r setup, echo = FALSE}
library(knitr)
opts_chunk$set(message = FALSE, warning = FALSE, cache = TRUE, fig.align = "center")
```

```{r, cache = FALSE, echo = FALSE}
library(readr)
library(directlabels)
library(dplyr)
library(xtable)
library(tidyr)
library(magrittr)
library(readr)
library(langcog)
library(ggplot2)
library(zoo)
library(purrr)
library(broom)
library(lme4)
library(lmerTest)
```

```{r, echo = TRUE}
#CONSTANTS
TEST_START <- .5
TEST_END <- 4.5
LEARN_START <- 0
LEARN_END <- 9

COLORS <- c("#c6dbef","#6baed6","#2171b5","#08306b","#f16913","#6a51a3")

#raw_learn_data %>% group_by(Stimulus) %>% summarise(max_time = max(Time))
```

Load data
```{r load_data}
raw_learn_data <- read_csv(paste0("processed_data/csvs/soc_word/child/train_data.csv")) %>%
  filter(age >= 1 & age < 5) %>%
  mutate(age_group = factor(floor(age))) %>%
  mutate(group = "child") %>%
  mutate(object_type = factor(object_type, levels = c("extended", "brief"),
         labels = c("Extended Hold", "Brief Look")))

raw_test_data <- read_csv(paste0("processed_data/csvs/soc_word/child/test_data.csv")) %>%
  filter(age >= 1 & age < 5) %>%
  mutate(age_group = factor(floor(age))) %>%
  mutate(group = "child") %>%
  mutate(object_type = factor(object_type, levels = c("extended", "familiar", "brief"),
         labels = c("Extended Hold", "Familiar", "Brief Look")))
```

```{r calibration_kappas}
calibs <- read_csv("processed_data/calib_adjust/soc_word/child/calibs.csv")

calib_kappa <-kappa2(calibs[, c("coder1_include", "coder2_include")])

print(calib_kappa)
```

Exclude children as necessary
```{r exclusions}
# Count starting participants
start_ps <- raw_test_data %>%
  group_by(age_group) %>%
  distinct(subj) %>%
  summarise(initial_n = n())
  
# Count children with <75% exposure to English
dropped_english <- raw_test_data %>%
  filter(english < 75 | is.na(english)) %>%
  summarise(low_english = (length(unique(subj))))

# Count children who were born before the 37th week of pregnancy
dropped_premature <- raw_test_data %>%
  distinct(subj) %>%
  filter(premature | is.na(premature)) %>%
  summarise(premature = n())

# Exclude children
kept_ps <- raw_test_data %>%
  filter(english >= 75, !premature, !is.na(premature), !is.na(english)) 

kable(bind_cols(dropped_english, dropped_premature),
      caption = "Children matching exclusion criteria")

# Count the number of girls in each age group
count_girls <- kept_ps %>%
  group_by(age_group, gender) %>%
  distinct(subj) %>%
  filter(gender == "female") %>%
  summarise(female = n()) %>%
  select(-gender)

# Count remaining children in each group
count_ps <- kept_ps %>%
  group_by(age_group) %>%
  distinct(subj) %>%
  summarise(final_n = n(), mean_age = mean(age), min_age = min(age),
            max_age = max(age)) %>%
  left_join(count_girls)

final_ps <- left_join(start_ps, count_ps)

kable(final_ps, caption = "Final participants in each age group")

kept_learn_data <- raw_learn_data %>%
  filter(subj %in% unique(kept_ps$subj)) %>%
  select(-gender, -english, -premature)

kept_test_data <- raw_test_data %>%
  filter(subj %in% unique(kept_ps$subj)) %>%
  select(-gender, -english, -premature)
```

Exclude trials with >50% missing data, exclude participants with > 50% missing trials
```{r missing_data}
na_out_missing <- function(data, prop = .5) {
  
  max_trials <- length(unique(data$trial))
  
  na_props <- data %>%
    group_by(subj, trial) %>%
    summarise(na_prop = sum(is.na(aoi)) / length(aoi))
  
  complete_data <- na_props %>%
    filter(na_prop <= prop) %>%
    select(-na_prop) %>%
    left_join(data)
  
  missing_data <- na_props %>%
    filter(na_prop > prop) %>%
    select(-na_prop) %>%
    left_join(mutate(data, aoi = NA))
  
  missing_trials <- missing_data %>%
    group_by(subj) %>%
    summarise(num_trials = length(unique(trial))) %>%
    filter(num_trials > (max_trials * prop))
  
  together_data <- bind_rows(complete_data,missing_data)
  
  drop_subjs <- together_data %>%
    filter(subj %in% missing_trials$subj) %>%
    mutate(aoi = NA)
  
  bind_rows(filter(together_data, !subj %in% missing_trials$subj),
            drop_subjs) %>%
    arrange(subj, trial,Time) 
}

test_data <- na_out_missing(raw_test_data) 
learn_data <- na_out_missing(raw_learn_data) %>%
  filter(Time >=LEARN_START, Time <= LEARN_END)

na_exclusions <- function(data) {
  
  na_data <- data %>%
    group_by(group, subj, trial) %>%
    summarise(na_trial = (sum(is.na(aoi)/length(aoi))) == 1) %>%
    group_by(group, subj) %>%
    summarise(na_trial = mean(na_trial)) %>%
    mutate(na_subj = na_trial == 1)

  left_join(summarise(na_data, na_subj = mean(na_subj)),
            summarise(filter(na_data, !na_subj), na_trial = mean(na_trial)))
}

na_test_exclusions <- na_exclusions(test_data)
na_learn_exclusions <- na_exclusions(learn_data)

kable(na_test_exclusions)
kable(na_learn_exclusions)
```


Test timecourse data
```{r timecourse_data}
#summarize across individual trials
test_data_time <- test_data %>% 
  group_by(age_group, test_type, object_type, Time, subj) %>%
  summarise(correct = sum(aoi == "Target", na.rm = TRUE) / 
      (sum(aoi == "Target", na.rm = TRUE)+
         sum(aoi == "Competitor", na.rm = TRUE))) %>%
  summarise_each(funs(mean(., na.rm = T), sem(., na.rm = T)),correct) %>%
  rename(correct = mean) %>%
  group_by( age_group, object_type, Time) %>%
  mutate(roll_mean = rollapply(correct, 15, 
                               FUN = function(x) {mean(x, na.rm = T)},
                               partial = TRUE),
         roll_sem = rollapply(sem, 15, 
                              FUN = function(x) {mean(x, na.rm = T)},
                              partial = TRUE)) %>%
  rename(mean = correct)
```

Plot test timecourses
```{r test_timecourses, fig.width = 8, fig.height = 7}
ggplot(filter(test_data_time, Time == round(Time, 1), test_type == "NF"), 
       aes(x = Time, y = roll_mean, colour = age_group, 
           fill = age_group, 
           label = age_group))+
  facet_grid(object_type ~ .) +
  geom_ribbon(aes(ymin = roll_mean - roll_sem,
                      ymax = roll_mean + roll_sem),
                  size=0, alpha = .5)+
  geom_line()+
  geom_hline(aes(yintercept = .5), lty= "dashed")  +
#   geom_rect(aes(xmin = TEST_START, xmax = TEST_END, ymin = -Inf, ymax = Inf),
#             alpha = .01, fill = "lightgray", colour = NA) +
  geom_vline(aes(xintercept = TEST_START), lty= "dashed", color = "gray") + 
   geom_vline(aes(xintercept = TEST_END), lty= "dashed", color = "gray") + 
  scale_x_continuous(name = "Time", limits = c(-2, 4.5), breaks = seq(-2,4.5,1))+ 
  geom_vline(aes(xintercept = 0), lty = "dashed") +
  scale_y_continuous(limits = c(0,1), breaks=seq(0,1,.1),
                     name = "Prop. correct looks") +
  theme_bw(base_size = 16) + 
  theme(panel.grid = element_blank(), legend.position = "none",
        axis.title.x=element_text(vjust=-.5), axis.title.y=element_text(vjust=1)) +
  scale_color_manual(values = COLORS) +
  scale_fill_manual(values = COLORS) +
  geom_dl(method = list(dl.trans(x=x +.2), "last.qp", cex=1))
```

Train timecourse data
```{r train_timecourse_data}
#summarize across individual trials
learn_data_time <- learn_data %>% 
  group_by(age_group, object_type, Time, subj) %>%
  summarise(correct = sum(aoi == "Target", na.rm = TRUE) / 
      (sum(aoi == "Target", na.rm = TRUE)+
         sum(aoi == "Competitor", na.rm = TRUE) +
          sum(aoi == "Face", na.rm = TRUE))) %>%
  summarise_each(funs(mean(., na.rm = T), sem(., na.rm = T)),correct) %>%
  rename(correct = mean) %>%
  group_by( age_group, object_type, Time) %>%
  mutate(roll_mean = rollapply(correct, 15, 
                               FUN = function(x) {mean(x, na.rm = T)},
                               partial = TRUE),
         roll_sem = rollapply(sem, 15, 
                              FUN = function(x) {mean(x, na.rm = T)},
                              partial = TRUE)) %>%
  rename(mean = correct)
```

Accs and RTs
```{r train_timecourse_data}
#summarize across individual trials
include_trial_onset <- learn_data %>% 
  filter(Time == 0) %>%
  group_by(object_type, age_group, subj, trial ) %>%
  summarise(include = sum(aoi == "Face")) %>%
  filter(include == 1)

include_trial_target <- left_join(include_trial_onset, learn_data) %>%
  arrange(object_type, age_group, age, subj, trial, Time) %>%
  group_by(object_type, age_group, age, subj, trial, aoi) %>%
  distinct() %>%
  summarise(Time = mean(Time)) %>%
  filter(!is.na(aoi)) %>%
  spread(aoi, Time)

accs <- include_trial_target %>%
  summarise(correct = ((is.na(Competitor) & !is.na(Target)) | (Target < Competitor))) %>%
  summarise(correct = mean(correct, na.rm = T)) %>%
  summarise(correct = mean(correct, na.rm = T)) %>%
  summarise(correct = mean(correct, na.rm = T), n = n(), age = mean(age))

rts <- include_trial_target %>%
  filter((is.na(Competitor) & !is.na(Target)) | (Target < Competitor)) %>%
  summarise(rt = mean(Target)) %>%
  summarise(rt = mean(rt)) %>%
  summarise(rt = mean(rt)) %>%
  summarise(rt = mean(rt))

soc_word_data <- left_join(accs, rts)
```



```{r train_timecourses, fig.width = 8, fig.height = 3.5}
ggplot(filter(learn_data_time, Time == round(Time, 1)), 
       aes(x = Time, y = roll_mean, colour = age_group, 
           fill = age_group, 
           label = age_group))+
  facet_grid(object_type ~ . ) +
  geom_ribbon(aes(ymin = roll_mean - roll_sem,
                      ymax = roll_mean + roll_sem),
                  size=0, alpha = .5)+
  geom_line()+
#   geom_rect(aes(xmin = TEST_START, xmax = TEST_END, ymin = -Inf, ymax = Inf),
#             alpha = .01, fill = "lightgray", colour = NA) +
  geom_vline(aes(xintercept = LEARN_START), lty= "dashed", color = "gray") + 
  geom_vline(aes(xintercept = LEARN_END), lty= "dashed", color = "gray") + 
  scale_x_continuous(name = "Time", limits = c(-1, 9.5), breaks = seq(-1,9.5,1))+ 
  geom_vline(aes(xintercept = 0), lty = "dashed") +
  scale_y_continuous(limits = c(0,1), breaks=seq(0,1,.1),
                     name = "Prop. correct looks") +
  theme_bw(base_size = 16) + 
  theme(panel.grid = element_blank(), legend.position = "none",
        axis.title.x=element_text(vjust=-.5), axis.title.y=element_text(vjust=1)) +
  scale_color_manual(values = COLORS) +
  scale_fill_manual(values = COLORS) +
  geom_dl(method = list(dl.trans(x=x +.2), "last.qp", cex=1))
```

Munge data to compute looking proportions
```{r munge_data}
test_data_subj <- test_data %>% 
  filter(Time >= TEST_START, 
         Time <= TEST_END) %>%
  group_by(age_group, age, subj, test_type, object_type, trial) %>%
  summarise(
    prop = sum(aoi == "Target", na.rm = TRUE) / 
      (sum(aoi == "Target", na.rm = TRUE)+
         sum(aoi == "Competitor", na.rm = TRUE))) %>%
  summarise(prop = mean(prop, na.rm = TRUE))

learn_data_subj <- learn_data %>%
  group_by(age_group, object_type, age, subj, trial) %>%
  summarise(
    prop = sum(aoi == "Target", na.rm = T)/
      (sum(aoi == "Target", na.rm = T) + 
         sum(aoi == "Competitor", na.rm = T) + 
         sum(aoi == "Face", na.rm = T))) %>%
  summarise(prop = mean(prop, na.rm = TRUE))

test_data_age_group <- test_data_subj %>%
  group_by(age_group, test_type, object_type) %>%
  multi_boot_standard("prop", na.rm = TRUE)

kable(test_data_age_group)

learn_data_age_group <- learn_data_subj %>%
  group_by(age_group, object_type) %>%
  multi_boot_standard("prop", na.rm = TRUE)

kable(learn_data_age_group)

```

Test plot
```{r test_dot_plot, fig.width = 5.5, fig.height = 4}
quartz(width = 5.5, height = 4)
ggplot(filter(test_data_age_group, test_type == "NF"),
       aes(x = age_group, y = mean, colour = object_type, label = object_type,
           group = object_type))+
  #facet_grid(~ test_type) + 
  geom_pointrange(aes(ymin = ci_lower,
                      ymax = ci_upper),
                  size=.7, position = position_dodge(.1))+
  geom_hline(aes(yintercept=.5),lty=2)  +
  geom_line(position = position_dodge(.1)) +
  scale_x_discrete(name = "Age (years)") + 
  scale_y_continuous(limits = c(.4,.9), breaks=seq(.4,.9,.1),
                    name = "Prop. Looks to Target") +
  theme_bw(base_size=16) + 
  expand_limits(x = 5.5) +
  theme(legend.position="none", legend.title=element_blank(),
        panel.grid=element_blank(), axis.title.x=element_text(vjust=-.5),
        axis.title.y=element_text(vjust=1)) +
  geom_dl(method = list(dl.trans(x=x +.3), "last.qp", cex=1)) +
  scale_color_brewer(palette = "Set1") 

quartz(width = 5.5, height = 4)
ggplot(filter(test_data_age_group, test_type == "NN"),
       aes(x = age_group, y = mean, colour = object_type, label = object_type,
           group = object_type))+
  #facet_grid(~ test_type) + 
  geom_pointrange(aes(ymin = ci_lower,
                      ymax = ci_upper),
                  size=.7, position = position_dodge(.1))+
  geom_hline(aes(yintercept=.5),lty=2)  +
  geom_line(position = position_dodge(.1)) +
  scale_x_discrete(name = "Age (years)") + 
  scale_y_continuous(limits = c(.3,.9), breaks=seq(.4,.9,.1),
                    name = "Prop. Looks to Target") +
  theme_bw(base_size=16) + 
  expand_limits(x = 5.5) +
  theme(legend.position="none", legend.title=element_blank(),
        panel.grid=element_blank(), axis.title.x=element_text(vjust=-.5),
        axis.title.y=element_text(vjust=1)) +
  geom_dl(method = list(dl.trans(x=x +.3), "last.qp", cex=1)) +
  scale_color_brewer(palette = "Set1") 
```

Learn plots
```{r learn_dot_plot}
ggplot(learn_data_age_group, 
       aes(x = age_group, y = mean, colour = object_type, label = object_type,
           group = object_type))+
  geom_pointrange(aes(ymin = ci_lower,
                      ymax = ci_upper),
                  size=.8, position = position_dodge(.1))+
  geom_hline(aes(yintercept=.5),lty=2)  +
  geom_line(position = position_dodge(.1)) +
  scale_x_discrete(name = "Participant group")+ 
#   scale_y_continuous(limits = c(0,1), breaks=seq(0,1,.1),
#                      name = "Prop. Looks to Target vs. Competitor") +
  theme_bw(base_size=18) + 
    theme(legend.position="none", legend.title=element_blank(),
        panel.grid=element_blank(), axis.title.x=element_text(vjust=-.5),
        axis.title.y=element_text(vjust=1)) +
  geom_dl(method = list(dl.trans(x=x +.2), "last.qp", cex=1)) +
  scale_color_brewer(palette = "Set1") 
```

  
```{r model_setup}
familiars <- test_data_subj %>%
  filter(object_type == "Familiar") %>%
  summarise(Familiar = mean(prop, na.rm = T)) %>%
  select(-test_type)

dependent <- test_data_subj %>%
  filter(object_type != "Familiar") %>%
  spread(object_type, prop) %>%
  gather(object_type, test, c(`Brief Look`, `Extended Hold`)) %>%
  left_join(familiars)

model_data <- left_join(dependent, learn_data_subj)
```



```{r models}
# Age differences during learning
learn_corrs <- learn_data_subj %>%
  split(.$object_type) %>%
  map(~tidy(cor.test(.$age, .$prop, use = "complete"))) %>%
  bind_rows(.id = "object_type") %>%
  select(-statistic) %>%
  rename(r = estimate, df = parameter)
kable(learn_corrs)

# Compare learning to test
age_test_nulls <- test_data_subj %>%
  split(paste(.$age_group, .$test_type, .$object_type, sep = "-")) %>%
  map(~tidy(t.test(x = .$prop, mu = .5))) %>%
  bind_rows(.id = "id") %>%
  separate(id, c("group", "test_type", "object_type"), sep = "-") %>%
  rename(mu = estimate, t = statistic, df = parameter)
kable(age_test_nulls)

#tests
age_test_types <- lmer(prop ~ age + object_type + test_type + (1|subj), 
                       data = test_data_subj)
kable(summary(age_test_types)$coefficients)


#tests--NF only
age_test_types_NF <- lmer(prop ~ age + object_type + (1|subj), 
                       data = filter(test_data_subj, test_type == "NF"))


#tests--NF only, include Familiar, interaction
test_model_NF <- lmer(test ~ age + object_type + Familiar + (1|subj), 
                       data = filter(model_data, test_type == "NF"))

#tests--NF only, include Familiar
test_model_NF_int <- lmer(test ~ age + object_type * Familiar + (1|subj), 
                       data = filter(model_data, test_type == "NF"))

kable(anova(test_model_NF,test_model_NF_int))

summary(test_model_NF_int)

kable(summary(test_model_NF)$coefficients)

# Compare object_type across ages
age_group_object_types <- lmer(test ~ Familiar + as.factor(age_group)*object_type +
                                 Familiar + (1|subj), 
                               data = filter(model_data, object_type != "Familiar",
                                             test_type == "NF"))
kable(summary(age_group_object_types)$coefficients)




# Age differences by window_type
test_corrs <- model_data %>%
  split(paste(.$object_type, .$test_type, .$window_type, sep = "-")) %>%
  map(~tidy(cor.test(.$test, .$prop, use = "complete"))) %>%
  bind_rows(.id = "id") %>%
  separate(id, c("object_type", "test_type", "window_type"), sep = "-")
kable(test_corrs)
# 
# model <- lmer(test ~ prop + (1|subj),  
#               data = filter(model_data, window_type == "long"))
# 
# dat <- filter(model_data, window_type == "long")
# 
# cor(dat$test, dat$prop, use = "complete")
# cor(dat$test, dat$Familiar, use = "complete")
# cor(dat$test, dat$age, use = "complete")
# cor(dat$prop, dat$object_type == "Extended Hold", use = "complete")
# 
# 
# 
# cor(filter(model_data, window_type == "short")$test,
#     filter(model_data, window_type == "short")$prop, use = "complete")
# 
# 
# model <- lmer(test ~ Familiar + age + object_type + (1|subj),
#               data = filter(model_data, window_type == "short"))
# 
# resid_data <- filter(model_data, !is.na(test))
# resid_data$resid <- residuals(lm(test ~ age + object_type , data = resid_data))
# 
# tmp <- filter(resid_data, window_type == "long")
# cor(tmp$resid, tmp$z_prop, use = "complete")

# # 
# # resid_models <- resid_data %>%
# #   split(.$window_type) %>%
# #   map(~lmer(resid ~ prop + familiar + object_type + (1|subj), data = .)) %>%
# #   map(coeff_table) %>%
# #   bind_rows(.id = "window_type")
# 
# 
# resid_models <- resid_data %>%
#   filter(object_type == "extended") %>%
#   split(.$window_type) %>%
#   map(~lm(resid ~ prop + familiar, data = .)) %>%
#   map(coeff_table) %>%
#   bind_rows(.id = "window_type")
# 
# kable(resid_models)
```